/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Election {
  export type CandidateStruct = {
    id: string;
    name: string;
    voteCount: BigNumberish;
  };

  export type CandidateStructOutput = [
    id: string,
    name: string,
    voteCount: bigint
  ] & { id: string; name: string; voteCount: bigint };
}

export interface ElectionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCandidate"
      | "candidateIds"
      | "candidates"
      | "getAllCandidates"
      | "getCandidate"
      | "owner"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CandidateAdded" | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCandidate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "candidateIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "candidates", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAllCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidate",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "vote", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "addCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "candidateIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "candidates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace CandidateAddedEvent {
  export type InputTuple = [id: string, name: string];
  export type OutputTuple = [id: string, name: string];
  export interface OutputObject {
    id: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [candidateId: string, newVoteCount: BigNumberish];
  export type OutputTuple = [candidateId: string, newVoteCount: bigint];
  export interface OutputObject {
    candidateId: string;
    newVoteCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Election extends BaseContract {
  connect(runner?: ContractRunner | null): Election;
  waitForDeployment(): Promise<this>;

  interface: ElectionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCandidate: TypedContractMethod<
    [_id: string, _name: string],
    [void],
    "nonpayable"
  >;

  candidateIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  candidates: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint] & { id: string; name: string; voteCount: bigint }
    ],
    "view"
  >;

  getAllCandidates: TypedContractMethod<
    [],
    [Election.CandidateStructOutput[]],
    "view"
  >;

  getCandidate: TypedContractMethod<
    [_id: string],
    [[string, string, bigint]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  vote: TypedContractMethod<[_candidateId: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCandidate"
  ): TypedContractMethod<[_id: string, _name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "candidateIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "candidates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint] & { id: string; name: string; voteCount: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllCandidates"
  ): TypedContractMethod<[], [Election.CandidateStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getCandidate"
  ): TypedContractMethod<[_id: string], [[string, string, bigint]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<[_candidateId: string], [void], "nonpayable">;

  getEvent(
    key: "CandidateAdded"
  ): TypedContractEvent<
    CandidateAddedEvent.InputTuple,
    CandidateAddedEvent.OutputTuple,
    CandidateAddedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "CandidateAdded(string,string)": TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;
    CandidateAdded: TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;

    "VoteCast(string,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
